name: Build and Publish Docker Image (Pre-Release)

on:
  release:
    types: [prereleased]

jobs:
  call-workflow-build:
    uses: OpenOlitor/openolitor-client-kundenportal/.github/workflows/grunt-build.yml@fix/deps_node16
  docker:
    name: Build Docker Image ($Version only)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: client-kundenportal-dist
    - name: Set env
      run: echo VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV
    - name: Docker Login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build Docker Image
      run: docker build . -t openolitor/openolitor-client-kundenportal:$VERSION
    - name: Publish Docker Image (versioned)
      run: docker push openolitor/openolitor-client-kundenportal:$VERSION
