name: Build and Publish Docker Image (Release)

on:
  workflow_run:
    workflows: ["Build Webapp"]
    types:
      - completed
  release:
    types: [released]

jobs:
  docker:
    name: Build Docker Image ($Version and latest)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: client-kundenportal-dist
    - name: Set env
      run: echo VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV
    - name: Docker Login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build Docker Image (versioned)
      run: docker build . -t openolitor/openolitor-client-kundenportal:$VERSION
    - name: Publish Docker Image (versioned)
      run: docker push openolitor/openolitor-client-kundenportal:$VERSION
    - name: Build Docker Image (latest)
      run: docker build . -t openolitor/openolitor-client-kundenportal:latest
    - name: Publish Docker Image (latest)
      run: docker push openolitor/openolitor-client-kundenportal:latest
