name: Build Webapp

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fix up git URLs
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: fetch npm v7
      run: npm install -g npm@latest-7
      with:
        npm_config_legacy_peer_deps: true
    - name: Fetch bower
      run: npm install -g bower grunt-cli
    - name: npm ci
      run: npm ci --prefer-offline
    - name: bower install
      run: bower install --allow-root
    - name: Run Build
      run: buildDate=`date +%Y%m%d` && grunt build --buildnr=$buildDate
    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: client-kundenportal-dist
        path: dist
